---
- name: Install Erlang and RabbitMQ
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - erlang-common-test
          - erlang-crypto
          - erlang-public-key
          - erlang-snmp
          - erlang-ssh
          - erlang-ssl
          - erlang-wx
          - libwxgtk3.0-0v5
        state: present
      ignore_errors: yes

    - name: Add repository for Erlang
      apt_repository:
        repo: deb http://binaries.erlang-solutions.com/debian {{ ansible_distribution_release }} contrib
        state: present
      register: erlang_repo

    - name: Add Erlang Solutions public key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present
      when: erlang_repo.changed

    - name: Update package lists (after adding Erlang repo)
      apt:
        update_cache: yes
      when: erlang_repo.changed

    - name: Install Erlang
      apt:
        name: erlang
        version: 1:25.2.2-2
        state: present

    - name: Add RabbitMQ repository
      apt_repository:
        repo: deb https://dl.bintray.com/rabbitmq-erlang/debian {{ ansible_distribution_release }} main
        state: present
      register: rabbitmq_repo

    - name: Add RabbitMQ public key
      apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
        state: present
      when: rabbitmq_repo.changed

    - name: Update package lists (after adding RabbitMQ repo)
      apt:
        update_cache: yes
      when: rabbitmq_repo.changed

    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present

    - name: Enable and start RabbitMQ service
      systemd:
        name: rabbitmq-server
        state: started
        enabled: yes

