---
- name: Setup Nginx svc
  hosts: websrvgrp
  gather_facts: no
  tasks:
    - name: update
      apt: update_cache=yes   
   
    - name: Install Nginx
      apt: name=nginx state=latest

      notify:
        - restart nginx

    - name: Disable Nginx default website
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      tags:
        - conf

    - name: Deploy web config file
      template:
        src: /home/ubuntu/Full_Stack_Project/AWS_VPC_Complete_Stack_Deployment-Terraform/templates/nginxdpro.j2
        dest: /etc/nginx/sites-available/vproapp
      tags:
        - conf

    - name: Enable vproapp website
      file:
        src: /etc/nginx/sites-available/vproapp
        dest: /etc/nginx/sites-enabled/vproapp
        state: link
      notify:
        - Restart Nginx
      tags:
        - conf

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

